2025-06-05 17:32:00.689663: W external/xla/xla/service/hlo_rematerialization.cc:3005] Can't reduce memory use below 56.51GiB (60680469578 bytes) by rematerialization; only reduced to 84.31GiB (90522791134 bytes), down from 84.31GiB (90522880646 bytes) originally
2025-06-05 17:32:20.663993: W external/xla/xla/tsl/framework/bfc_allocator.cc:482] Allocator (GPU_0_bfc) ran out of memory trying to allocate 76.11GiB (rounded to 81721667840)requested by op 
2025-06-05 17:32:20.664340: W external/xla/xla/tsl/framework/bfc_allocator.cc:494] *___________________________________________________________________________________________________
E0605 17:32:20.664393  404985 pjrt_stream_executor_client.cc:2985] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 81721667800 bytes.
Number of full points in MOA: 422
Number of full points in OGLE: 15
jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/miyazaki/work/microjax/example/OGLE-2014-BLG-1722/4_hmc.py", line 155, in <module>
    mcmc.run(jax.random.PRNGKey(0), data_moa=data_moa, data_ogle=data_ogle, parallax_params=parallax_params)
  File "/home/miyazaki/.pyenv/versions/miniforge3-4.14.0-2/lib/python3.10/site-packages/numpyro/infer/mcmc.py", line 702, in run
    states_flat, last_state = partial_map_fn(map_args)
  File "/home/miyazaki/.pyenv/versions/miniforge3-4.14.0-2/lib/python3.10/site-packages/numpyro/infer/mcmc.py", line 465, in _single_chain_mcmc
    new_init_state = self.sampler.init(
  File "/home/miyazaki/.pyenv/versions/miniforge3-4.14.0-2/lib/python3.10/site-packages/numpyro/infer/hmc.py", line 751, in init
    init_params = self._init_state(
  File "/home/miyazaki/.pyenv/versions/miniforge3-4.14.0-2/lib/python3.10/site-packages/numpyro/infer/hmc.py", line 695, in _init_state
    ) = initialize_model(
  File "/home/miyazaki/.pyenv/versions/miniforge3-4.14.0-2/lib/python3.10/site-packages/numpyro/infer/util.py", line 750, in initialize_model
    (init_params, pe, grad), is_valid = find_valid_initial_params(
  File "/home/miyazaki/.pyenv/versions/miniforge3-4.14.0-2/lib/python3.10/site-packages/numpyro/infer/util.py", line 472, in find_valid_initial_params
    (init_params, pe, z_grad), is_valid = _find_valid_params(
  File "/home/miyazaki/.pyenv/versions/miniforge3-4.14.0-2/lib/python3.10/site-packages/numpyro/infer/util.py", line 458, in _find_valid_params
    _, _, (init_params, pe, z_grad), is_valid = init_state = body_fn(init_state)
  File "/home/miyazaki/.pyenv/versions/miniforge3-4.14.0-2/lib/python3.10/site-packages/numpyro/infer/util.py", line 440, in body_fn
    z_grad = jacfwd(potential_fn)(params)
  File "/home/miyazaki/.pyenv/versions/miniforge3-4.14.0-2/lib/python3.10/site-packages/jax/_src/api.py", line 810, in jacfun
    y, jac = vmap(pushfwd, out_axes=(None, -1))(_std_basis(dyn_args))
  File "/home/miyazaki/.pyenv/versions/miniforge3-4.14.0-2/lib/python3.10/site-packages/numpyro/infer/util.py", line 324, in potential_energy
    log_joint, model_trace = log_density_(
  File "/home/miyazaki/.pyenv/versions/miniforge3-4.14.0-2/lib/python3.10/site-packages/numpyro/infer/util.py", line 120, in log_density
    log_joint, model_trace = compute_log_probs(model, model_args, model_kwargs, params)
  File "/home/miyazaki/.pyenv/versions/miniforge3-4.14.0-2/lib/python3.10/site-packages/numpyro/infer/util.py", line 78, in compute_log_probs
    model_trace = trace(model).get_trace(*model_args, **model_kwargs)
  File "/home/miyazaki/.pyenv/versions/miniforge3-4.14.0-2/lib/python3.10/site-packages/numpyro/handlers.py", line 191, in get_trace
    self(*args, **kwargs)
  File "/home/miyazaki/.pyenv/versions/miniforge3-4.14.0-2/lib/python3.10/site-packages/numpyro/primitives.py", line 121, in __call__
    return self.fn(*args, **kwargs)
  File "/home/miyazaki/.pyenv/versions/miniforge3-4.14.0-2/lib/python3.10/site-packages/numpyro/primitives.py", line 121, in __call__
    return self.fn(*args, **kwargs)
  File "/home/miyazaki/.pyenv/versions/miniforge3-4.14.0-2/lib/python3.10/site-packages/numpyro/primitives.py", line 121, in __call__
    return self.fn(*args, **kwargs)
  [Previous line repeated 3 more times]
  File "/home/miyazaki/work/microjax/example/OGLE-2014-BLG-1722/4_hmc.py", line 141, in model
    nll = nll_fn(params, data_moa, data_ogle, parallax_params)
  File "/home/miyazaki/work/microjax/example/OGLE-2014-BLG-1722/4_hmc.py", line 80, in nll_fn
    mags_moa = mag_time(t_moa, params, parallax_params,
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 81721667800 bytes.
